
from pieces import *


# Tests
print('Piece Tests:')
p1 = Piece(0, 0, 1)
print(f"Color: {p1.get_color()}")
print(f"Worth: {p1.get_worth()}")
print(f"Position: {p1.get_position()}")
p1.move(3, 4)
print(F"Legal moves: {p1.legal_moves()}")


print('\nRook Tests:')
r = Rook(0, 0, -1)  # 0 = "black"
print(f"Color: {r.get_color()}")
print(f"Worth: {r.get_worth()}")
print(f"{r}: {r.get_position()}")
print(F"Legal moves: {r.legal_moves()}")
print(F"Was moved?: {r.get_was_moved()}")
r.move(3, 0)
print(f"{r}: {r.get_position()}")
print(F"Legal moves: {r.legal_moves()}")
print(F"Was moved?: {r.get_was_moved()}")
# r.move(7, 3)  # should be invalid move
# print(f"{r}: {r.get_position()}")
r.move(3, 3)
print(f"{r}: {r.get_position()}")
print(F"Legal moves: {r.legal_moves()}")
# r.move(9, 3)  # should be invalid board placement
# print(f"{r}: {r.get_position()}")

print('\nKing Tests:')
k = King(0, 0, 1)  # 1 = "white"
print(f"Color: {k.get_color()}")
print(f"Worth: {k.get_worth()}")
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
k.move(1, 1)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
# k.move(3, 3)  # should be invalid move
# print(f"{k}: {k.get_position()}")
k.move(2, 1)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
k.move(1, 1)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
k.move(0, 1)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
# k.move(-1, 1)  # should be invalid board placement
# print(f"{k}: {k.get_position()}")
k.move(1, 1)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
k.move(2,0)
k.move(3,0)
k.move(4,0)
k.move(5,0)
k.move(6,0)
k.move(7,0)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")
k.move(7,1)
k.move(7,2)
k.move(7,3)
k.move(7,4)
k.move(7,5)
k.move(7,6)
k.move(7,7)
print(f"{k}: {k.get_position()}")
print(F"Legal moves: {k.legal_moves()}")

print('\nBishop Tests:')
b = Bishop(3, 0, -1)
print(f"Color: {b.get_color()}")
print(f"Worth: {b.get_worth()}")
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
b.move(4, 1)
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
b.move(5, 2)
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
b.move(4, 1)
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
# b.move(3, 1)  # should be invalid move
# print(f"{b}: {b.get_position()}")
b.move(3, 2)
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
b.move(4, 3)
print(f"{b}: {b.get_position()}")
print(F"Legal moves: {b.legal_moves()}")
# b.move(4, 1)  # should be invalid move
# print(f"{b}: {b.get_position()}")

print('\nQueen Tests:')
q = Queen(0, 0, -1)
print(f"Color: {q.get_color()}")
print(f"Worth: {q.get_worth()}")
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
q.move(7, 0)
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
q.move(7, 2)
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
q.move(6, 1)
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
q.move(4, 3)
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
# q.move(5, 1)  # should be invalid move
# print(f"{q}: {q.get_position()}")
q.move(5, 2)
print(f"{q}: {q.get_position()}")
print(F"Legal moves: {q.legal_moves()}")
# q.move(9, 0)  # should be invalid board placement
# print(f"{q}: {q.get_position()}")

print('\nKnight Tests:')
n = Knight(0, 0, 1)
print(f"Color: {n.get_color()}")
print(f"Worth: {n.get_worth()}")
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
n.move(1, 2)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
# n.move(1, 3)  # should be invalid move
# print(f"{n}: {n.get_position()}")
n.move(0, 4)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
n.move(1, 6)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
# n.move(2, 6)  # should be invalid move
# print(f"{n}: {n.get_position()}")
n.move(2, 4)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
n.move(4, 5)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")
# n.move(1, 9)  # should be invalid move
# print(f"{n}: {n.get_position()}")
n.move(6, 6)
print(f"{n}: {n.get_position()}")
print(F"Legal moves: {n.legal_moves()}")

print('\nPawn Tests:')
p = Pawn(3, 1, 1)
print(f"Color: {p.get_color()}")
print(f"Worth: {p.get_worth()}")
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")
p.move(3, 3)
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")
p.move(3, 4)
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")


print('\n')
p = Pawn(3, 6, -1)
print(f"Color: {p.get_color()}")
print(f"Worth: {p.get_worth()}")
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")
p.move(3, 5)
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")
# p.move(3, 3) # should be invalid move
p.move(3, 4)
print(f"{p}: {p.get_position()}")
print(F"Legal moves: {p.legal_moves()}")
